repos:
-   repo: local
    hooks:
    -   id: export_schema
        name: Update GraphQL schema
        entry: poetry run update_schema
        language: python
        types: [python]
    -   id: isort
        name: Running isort
        entry: isort
        language: python
        types: [python]
    -   id: black
        entry: black
        name: Running black
        language: python
        types: [python]
    -   id: flake8
        name: Running flake8
        entry: flake8 --count
        language: python
        types: [python]
    -   id: mypy
        name: Running mypy
        entry: mypy
        language: python
        types: [python]
    -   id: pytest-cov
        name: Running pytest with coverage
        entry: pytest --cov
        language: python
        always_run: true
        pass_filenames: false
    -   id: commitizen
        name: Running commitizen
        entry: cz check --commit-msg-file
        language: system
        stages: [commit-msg]
